[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m venv venv",
  "source venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "source venv/bin/activate && python api_server.py" 