[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.flask",
  "python311Packages.flask-cors",
  "python311Packages.pillow",
  "python311Packages.tqdm",
  "python311Packages.numpy",
  "python311Packages.werkzeug",
  "python311Packages.gunicorn"
]

[phases.install]
cmds = ["echo 'Dependencies installed via Nix'"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python api_server.py" 