[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r api_requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python api_server.py" 